### ISSUE TITLE
[Matomo 4.1.0-b1][PHP8.0] mb_convert_encoding(): Unable to detect character encoding

### ISSUE THREAD

**Issue by MichaIng** [piwik/plugin-LogViewer#27]
I upgraded Matomo to the first beta of 4.1.0 and sadly as well migrated to PHP8.0, so I'm not quite sure which one of both is responsible for the error messages I get now:
```
WARNING | API | 2020-12-18 21:33:00 UTC | 5fbe4 | /var/www/matomo/core/DataTable/Renderer/Json.php(101): Warning - mb_convert_encoding(): Unable to detect character encoding - Matomo 4.1.0-b1
WARNING | API | 2020-12-18 21:33:00 UTC | 5fbe4 | /var/www/matomo/core/DataTable/Renderer/Json.php(101): Warning - mb_convert_encoding(): Unable to detect character encoding - Matomo 4.1.0-b1
```
Those two error messages appear every time I access the logs viewer, and only when accessing it, so it seems to be indeed a logs viewer bug or incompatibility with either Matomo 4.1.0 or PHP8.0.

Advise me, if you need further tests or (debug) logs.

**Comment by tsteur** [comment]
Hi @MichaIng 

I'd say it's likely due to PHP8. Maybe some `mbstring` php ini settings changed (https://www.php.net/manual/en/mbstring.configuration.php)

Any chance you still have your old system running and compare the output of the PHP Info page (or `php -i` command)? From what PHP version did you upgrade?

Do you maybe know of any special characters you are tracking? Like what language does the website you are tracking use?

**Comment by MichaIng** [comment]
It is strange, I cannot reproduce the error anymore. As it happened exactly when I accessed or reloaded the logs viewer, is it possible that it was a special character in the logs themselves?

I upgraded from PHP7.4 to PHP8.0 without any config changes, aside of changed defaults. No mbstring settings were or are set and I do not see that defaults changed with PHP8.0 🤔.
Website language is in Englisch and UTF-8 format, the tracker is implemented via Cloudflare Piwik app, hence no special variables or code added, if that plays a role.

Sadly I already purged the PHP7.4 configuration, so cannot reliably recover the exact PHP info from the previous setup. I'll keep an eye on the logs and see if it appears again, but until then I think it's okay to close the issue. It is a warning only, no error, and encoding is continued, though possibly from a wrong origin format: https://www.php.net/manual/en/function.mb-convert-encoding.php#91601

**Comment by tsteur** [comment]
Possible it was a character in the log viewer. Feel free to comment here any time again @MichaIng  and let us know if this happens again. Maybe see if you can spot anything odd in the log viewer should it happen again. Like if something looks like this or so ` ��`
