### ISSUE TITLE
Log Viewer: Improve the error message when no log writer is setup

### ISSUE THREAD

**Issue by KarthikRaja1388** [piwik/plugin-LogViewer#57]
When Log writer is not set in Matomo and accessing it is throwing an error "Something went wrong" which is not so useful and give any hint on what's wrong, instead a useful error message can be thrown which will be helpful.

![image](https://user-images.githubusercontent.com/26726594/179620874-344ded2d-f360-4fd2-af28-b55a4593eeb3.png)

**Comment by mritzmann** [comment]
![Bildschirmfoto 2023-12-06 um 09 32 43](https://github.com/matomo-org/plugin-LogViewer/assets/4533780/8fe39759-2af7-4b2f-b5e3-00db8d71b5d3)

Seems fixed.

**Comment by snake14** [comment]
Hi @mritzmann . Thank you for pointing that out. It does indeed appear to have been fixed. I see the same message when I test in my local Matomo install as well. I'm closing this issue.
