### ISSUE TITLE
When writing an annotation, the log view is not recording it

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/plugin-LogViewer#69]
Hello team,
Would it be possible to support the log of annotation written/edited/deleted within the log viewer?

**Comment by snake14** [comment]
Hi @Chardonneaur . Could you please provide some more information about what you're hoping for? Are you wanting additional logging functions for written/edited/deleted, similar to debug/info/warning/error?

**Comment by sgiehl** [comment]
@Chardonneaur This plugin is actually meant for viewing logs of errors/warnings. Our ActivityLog plugin already allows to see activities around annotations and similar stuff.

**Comment by Chardonneaur** [comment]
Thanks @snake14 and @sgiehl what would then be the info log about the database?

**Comment by sgiehl** [comment]
Info and debug logs might be shown when the log level is accordingly. But all of them have a technical background, whereas activities that are performed by the user aren't "technical" and more related to the activity log.
